import crypto from "crypto";

export const hash = (value) =>
  crypto.createHash("sha256").update(String(value)).digest("hex");

const hoursAgo = (hours) =>
  new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();

export function createSeed() {
  const users = [
    {
      id: "usr_admin",
      name: "Elena Cruz",
      email: "admin@agritrackture.com",
      password: hash("Admin@123"),
      role: "admin",
      phone: "+63 917 555 0100",
      avatar: "EC",
      location: {
        address: "AgriTrackture HQ, 8 Harvest Tower",
        city: "Quezon City",
        province: "Metro Manila",
        lat: 14.676,
        lng: 121.0437,
      },
      status: "active",
      createdAt: hoursAgo(720),
    },
    {
      id: "usr_farmer_1",
      name: "Rosa Mendoza",
      farmName: "Green Valley Farm",
      email: "rosa@agritrackture.com",
      password: hash("Farmer@123"),
      role: "farmer",
      phone: "+63 918 221 4470",
      avatar: "RM",
      location: {
        address: "Sitio Maligaya, Brgy. Palusapis",
        city: "Science City of Muñoz",
        province: "Nueva Ecija",
        lat: 15.7167,
        lng: 120.9,
      },
      verified: true,
      status: "active",
      createdAt: hoursAgo(400),
    },
    {
      id: "usr_farmer_2",
      name: "Juan Dela Cruz",
      farmName: "Highland Harvest",
      email: "juan@agritrackture.com",
      password: hash("Farmer@123"),
      role: "farmer",
      phone: "+63 927 334 8812",
      avatar: "JD",
      location: {
        address: "Km 5 Pico Road",
        city: "La Trinidad",
        province: "Benguet",
        lat: 16.455,
        lng: 120.59,
      },
      verified: true,
      status: "active",
      createdAt: hoursAgo(380),
    },
    {
      id: "usr_farmer_3",
      name: "Maria Santos",
      farmName: "Sunshine Orchard",
      email: "maria@agritrackture.com",
      password: hash("Farmer@123"),
      role: "farmer",
      phone: "+63 919 776 2201",
      avatar: "MS",
      location: {
        address: "Purok 4, Brgy. Bago Aplaya",
        city: "Davao City",
        province: "Davao del Sur",
        lat: 7.0731,
        lng: 125.6128,
      },
      verified: true,
      status: "active",
      createdAt: hoursAgo(300),
    },
    {
      id: "usr_farmer_4",
      name: "Pedro Ramirez",
      farmName: "Cornucopia Fields",
      email: "pedro@agritrackture.com",
      password: hash("Farmer@123"),
      role: "farmer",
      phone: "+63 915 442 1188",
      avatar: "PR",
      location: {
        address: "Purok 2, Brgy. Lumbo",
        city: "Valencia",
        province: "Bukidnon",
        lat: 7.9064,
        lng: 125.0942,
      },
      verified: false,
      status: "active",
      createdAt: hoursAgo(120),
    },
    {
      id: "usr_buyer_1",
      name: "Ana Reyes",
      email: "ana@agritrackture.com",
      password: hash("Buyer@123"),
      role: "buyer",
      phone: "+63 916 880 3344",
      avatar: "AR",
      location: {
        address: "22 Maginhawa Street",
        city: "Quezon City",
        province: "Metro Manila",
        lat: 14.647,
        lng: 121.058,
      },
      status: "active",
      createdAt: hoursAgo(90),
    },
    {
      id: "usr_buyer_2",
      name: "Carlo Lim",
      email: "carlo@agritrackture.com",
      password: hash("Buyer@123"),
      role: "buyer",
      phone: "+63 917 221 0098",
      avatar: "CL",
      location: {
        address: "Unit 12B, Poblacion",
        city: "Makati",
        province: "Metro Manila",
        lat: 14.5547,
        lng: 121.0244,
      },
      status: "active",
      createdAt: hoursAgo(70),
    },
    {
      id: "usr_buyer_3",
      name: "Lisa Tan",
      email: "lisa@agritrackture.com",
      password: hash("Buyer@123"),
      role: "buyer",
      phone: "+63 928 665 4410",
      avatar: "LT",
      location: {
        address: "Colon Street, Brgy. Santo Niño",
        city: "Cebu City",
        province: "Cebu",
        lat: 10.3157,
        lng: 123.8854,
      },
      status: "active",
      createdAt: hoursAgo(40),
    },
  ];

  const products = [
    {
      id: "prd_1",
      farmerId: "usr_farmer_1",
      name: "Premium White Rice",
      category: "Grains",
      description:
        "Newly milled NSIC Rc222 rice from irrigated paddies. Clean, aromatic, and ideal for daily household or restaurant use.",
      unit: "kg",
      price: 52,
      stock: 480,
      image:
        "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=1200&q=80",
      harvestDate: "2026-08-08",
      organic: false,
      status: "active",
      createdAt: hoursAgo(80),
    },
    {
      id: "prd_2",
      farmerId: "usr_farmer_1",
      name: "Red Onion",
      category: "Vegetables",
      description:
        "Firm red onions with strong flavor. Harvested this week and stored in ventilated crates.",
      unit: "kg",
      price: 78,
      stock: 160,
      image:
        "https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=1200&q=80",
      harvestDate: "2026-08-12",
      organic: false,
      status: "active",
      createdAt: hoursAgo(50),
    },
    {
      id: "prd_3",
      farmerId: "usr_farmer_2",
      name: "Highland Tomato",
      category: "Vegetables",
      description:
        "Sweet Benguet tomatoes grown in cool climate. Great for salads, salsas, and sauces.",
      unit: "kg",
      price: 72,
      stock: 95,
      image:
        "https://images.unsplash.com/photo-1546470427-227c7369c5b1?auto=format&fit=crop&w=1200&q=80",
      harvestDate: "2026-08-13",
      organic: true,
      status: "active",
      createdAt: hoursAgo(36),
    },
    {
      id: "prd_4",
      farmerId: "usr_farmer_2",
      name: "Crisp Cabbage",
      category: "Vegetables",
      description:
        "Heavy, tightly packed cabbage heads. Minimal pesticide and hand-harvested at dawn.",
      unit: "kg",
      price: 38,
      stock: 210,
      image:
        "https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?auto=format&fit=crop&w=1200&q=80",
      harvestDate: "2026-08-11",
      organic: true,
      status: "active",
      createdAt: hoursAgo(44),
    },
    {
      id: "prd_5",
      farmerId: "usr_farmer_3",
      name: "Lakatan Banana",
      category: "Fruits",
      description:
        "Ripe-ready Lakatan bananas from Davao. Naturally sweet with a bright yellow peel.",
      unit: "kg",
      price: 68,
      stock: 140,
      image:
        "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=1200&q=80",
      harvestDate: "2026-08-14",
      organic: false,
      status: "active",
      createdAt: hoursAgo(20),
    },
    {
      id: "prd_6",
      farmerId: "usr_farmer_3",
      name: "Carabao Mango",
      category: "Fruits",
      description:
        "Export-grade Carabao mangoes. Smooth, fiber-free flesh and honey-like sweetness.",
      unit: "kg",
      price: 145,
      stock: 60,
      image:
        "https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=1200&q=80",
      harvestDate: "2026-08-10",
      organic: false,
      status: "active",
      createdAt: hoursAgo(28),
    },
    {
      id: "prd_7",
      farmerId: "usr_farmer_4",
      name: "Yellow Corn",
      category: "Grains",
      description:
        "Fresh yellow corn from Bukidnon highlands. Suitable for feed, milling, or table use.",
      unit: "kg",
      price: 22,
      stock: 800,
      image:
        "https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=1200&q=80",
      harvestDate: "2026-08-09",
      organic: false,
      status: "active",
      createdAt: hoursAgo(18),
    },
    {
      id: "prd_8",
      farmerId: "usr_farmer_4",
      name: "Long Eggplant",
      category: "Vegetables",
      description:
        "Glossy long eggplants, tender and low-seed. Picked daily to keep freshness high.",
      unit: "kg",
      price: 48,
      stock: 75,
      image:
        "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=1200&q=80",
      harvestDate: "2026-08-14",
      organic: true,
      status: "active",
      createdAt: hoursAgo(10),
    },
  ];

  const guidePrices = [
    { id: "gp_1", name: "Premium White Rice", category: "Grains", unit: "kg", averagePrice: 50, minPrice: 45, maxPrice: 58, notes: "NFA and wet-market blended average.", updatedAt: hoursAgo(6) },
    { id: "gp_2", name: "Red Onion", category: "Vegetables", unit: "kg", averagePrice: 85, minPrice: 70, maxPrice: 110, notes: "Supply tightening in Central Luzon.", updatedAt: hoursAgo(6) },
    { id: "gp_3", name: "Highland Tomato", category: "Vegetables", unit: "kg", averagePrice: 70, minPrice: 55, maxPrice: 90, notes: "Benguet harvest currently stable.", updatedAt: hoursAgo(5) },
    { id: "gp_4", name: "Crisp Cabbage", category: "Vegetables", unit: "kg", averagePrice: 40, minPrice: 32, maxPrice: 52, notes: "Cool-weather crop, ample supply.", updatedAt: hoursAgo(5) },
    { id: "gp_5", name: "Lakatan Banana", category: "Fruits", unit: "kg", averagePrice: 65, minPrice: 55, maxPrice: 80, notes: "Mindanao farmgate plus logistics.", updatedAt: hoursAgo(4) },
    { id: "gp_6", name: "Carabao Mango", category: "Fruits", unit: "kg", averagePrice: 150, minPrice: 120, maxPrice: 180, notes: "Peak season quality premium.", updatedAt: hoursAgo(4) },
    { id: "gp_7", name: "Yellow Corn", category: "Grains", unit: "kg", averagePrice: 20, minPrice: 16, maxPrice: 26, notes: "Feed-grade and table-grade mix.", updatedAt: hoursAgo(3) },
    { id: "gp_8", name: "Long Eggplant", category: "Vegetables", unit: "kg", averagePrice: 45, minPrice: 35, maxPrice: 60, notes: "Daily vegetable market average.", updatedAt: hoursAgo(3) },
  ];

  const orders = [
    {
      id: "ord_1001",
      buyerId: "usr_buyer_1",
      farmerId: "usr_farmer_1",
      items: [{ productId: "prd_1", name: "Premium White Rice", qty: 25, unit: "kg", price: 52 }],
      total: 1300,
      status: "preparing",
      queuePosition: 1,
      notes: "Please mill extra-clean. Pickup Friday morning.",
      createdAt: hoursAgo(30),
      updatedAt: hoursAgo(4),
      statusHistory: [
        { status: "queued", at: hoursAgo(30), note: "Order placed by buyer" },
        { status: "confirmed", at: hoursAgo(28), note: "Farmer confirmed stock" },
        { status: "preparing", at: hoursAgo(4), note: "Milling in progress" },
      ],
    },
    {
      id: "ord_1002",
      buyerId: "usr_buyer_2",
      farmerId: "usr_farmer_1",
      items: [{ productId: "prd_2", name: "Red Onion", qty: 10, unit: "kg", price: 78 }],
      total: 780,
      status: "queued",
      queuePosition: 2,
      notes: "Need for weekend service.",
      createdAt: hoursAgo(8),
      updatedAt: hoursAgo(8),
      statusHistory: [{ status: "queued", at: hoursAgo(8), note: "Order placed by buyer" }],
    },
    {
      id: "ord_1003",
      buyerId: "usr_buyer_1",
      farmerId: "usr_farmer_2",
      items: [
        { productId: "prd_3", name: "Highland Tomato", qty: 8, unit: "kg", price: 72 },
        { productId: "prd_4", name: "Crisp Cabbage", qty: 6, unit: "kg", price: 38 },
      ],
      total: 804,
      status: "ready",
      queuePosition: 1,
      notes: "Restaurant restock.",
      createdAt: hoursAgo(20),
      updatedAt: hoursAgo(2),
      statusHistory: [
        { status: "queued", at: hoursAgo(20), note: "Order placed by buyer" },
        { status: "confirmed", at: hoursAgo(18), note: "Accepted" },
        { status: "preparing", at: hoursAgo(10), note: "Sorted and packed" },
        { status: "ready", at: hoursAgo(2), note: "Ready for pickup at farm stall" },
      ],
    },
    {
      id: "ord_1004",
      buyerId: "usr_buyer_3",
      farmerId: "usr_farmer_3",
      items: [{ productId: "prd_5", name: "Lakatan Banana", qty: 15, unit: "kg", price: 68 }],
      total: 1020,
      status: "completed",
      queuePosition: 0,
      notes: "",
      createdAt: hoursAgo(72),
      updatedAt: hoursAgo(24),
      statusHistory: [
        { status: "queued", at: hoursAgo(72), note: "Order placed by buyer" },
        { status: "confirmed", at: hoursAgo(70), note: "Accepted" },
        { status: "preparing", at: hoursAgo(48), note: "Packed" },
        { status: "ready", at: hoursAgo(36), note: "Ready" },
        { status: "completed", at: hoursAgo(24), note: "Buyer collected produce" },
      ],
    },
    {
      id: "ord_1005",
      buyerId: "usr_buyer_2",
      farmerId: "usr_farmer_3",
      items: [{ productId: "prd_6", name: "Carabao Mango", qty: 5, unit: "kg", price: 145 }],
      total: 725,
      status: "confirmed",
      queuePosition: 1,
      notes: "Prefer slightly ripe.",
      createdAt: hoursAgo(12),
      updatedAt: hoursAgo(9),
      statusHistory: [
        { status: "queued", at: hoursAgo(12), note: "Order placed by buyer" },
        { status: "confirmed", at: hoursAgo(9), note: "Trees tagged for harvest" },
      ],
    },
    {
      id: "ord_1006",
      buyerId: "usr_buyer_3",
      farmerId: "usr_farmer_4",
      items: [{ productId: "prd_7", name: "Yellow Corn", qty: 50, unit: "kg", price: 22 }],
      total: 1100,
      status: "queued",
      queuePosition: 1,
      notes: "For small store weekly stock.",
      createdAt: hoursAgo(3),
      updatedAt: hoursAgo(3),
      statusHistory: [{ status: "queued", at: hoursAgo(3), note: "Order placed by buyer" }],
    },
  ];

  const conversations = [
    {
      id: "con_1",
      farmerId: "usr_farmer_1",
      buyerId: "usr_buyer_1",
      lastMessage: "Rice will be milled by 8am. Farm is along Palusapis road.",
      lastAt: hoursAgo(3),
    },
    {
      id: "con_2",
      farmerId: "usr_farmer_2",
      buyerId: "usr_buyer_1",
      lastMessage: "Cabbage and tomatoes are packed. See you at the farm stall.",
      lastAt: hoursAgo(2),
    },
    {
      id: "con_3",
      farmerId: "usr_farmer_3",
      buyerId: "usr_buyer_2",
      lastMessage: "I can set aside the riper mangoes as requested.",
      lastAt: hoursAgo(7),
    },
  ];

  const messages = [
    { id: "msg_1", conversationId: "con_1", senderId: "usr_buyer_1", text: "Hi Rosa, can I pick up the rice this Friday?", createdAt: hoursAgo(29) },
    { id: "msg_2", conversationId: "con_1", senderId: "usr_farmer_1", text: "Yes, Friday morning works. I'll mill a clean 25kg sack.", createdAt: hoursAgo(28) },
    { id: "msg_3", conversationId: "con_1", senderId: "usr_farmer_1", text: "Rice will be milled by 8am. Farm is along Palusapis road.", createdAt: hoursAgo(3) },
    { id: "msg_4", conversationId: "con_2", senderId: "usr_buyer_1", text: "Juan, is the tomato order ready?", createdAt: hoursAgo(5) },
    { id: "msg_5", conversationId: "con_2", senderId: "usr_farmer_2", text: "Cabbage and tomatoes are packed. See you at the farm stall.", createdAt: hoursAgo(2) },
    { id: "msg_6", conversationId: "con_3", senderId: "usr_buyer_2", text: "Please choose mangoes that can ripen in 2 days.", createdAt: hoursAgo(11) },
    { id: "msg_7", conversationId: "con_3", senderId: "usr_farmer_3", text: "I can set aside the riper mangoes as requested.", createdAt: hoursAgo(7) },
  ];

  const notifications = [
    { id: "ntf_1", userId: "usr_admin", title: "New farmer registered", body: "Pedro Ramirez joined as Cornucopia Fields.", type: "user", read: false, createdAt: hoursAgo(120) },
    { id: "ntf_2", userId: "usr_admin", title: "Guide prices due for review", body: "Onion and mango averages were last checked today.", type: "pricing", read: false, createdAt: hoursAgo(4) },
    { id: "ntf_3", userId: "usr_farmer_1", title: "New order in queue", body: "Carlo Lim ordered 10kg Red Onion.", type: "order", read: false, createdAt: hoursAgo(8) },
    { id: "ntf_4", userId: "usr_farmer_1", title: "Buyer message", body: "Ana Reyes asked about Friday pickup.", type: "chat", read: true, createdAt: hoursAgo(29) },
    { id: "ntf_5", userId: "usr_buyer_1", title: "Order preparing", body: "Green Valley Farm is milling your rice order.", type: "order", read: false, createdAt: hoursAgo(4) },
    { id: "ntf_6", userId: "usr_buyer_1", title: "Order ready", body: "Highland Harvest packed your vegetables.", type: "order", read: false, createdAt: hoursAgo(2) },
    { id: "ntf_7", userId: "usr_buyer_2", title: "Order confirmed", body: "Sunshine Orchard confirmed your mangoes.", type: "order", read: true, createdAt: hoursAgo(9) },
    { id: "ntf_8", userId: "usr_farmer_4", title: "New order in queue", body: "Lisa Tan ordered 50kg Yellow Corn.", type: "order", read: false, createdAt: hoursAgo(3) },
    { id: "ntf_9", userId: "usr_farmer_2", title: "Order marked ready", body: "Ana Reyes can now collect tomatoes and cabbage.", type: "order", read: true, createdAt: hoursAgo(2) },
  ];

  const settings = {
    appName: "AgriTrackture",
    tagline: "Fair farm prices. Direct from the field.",
    supportEmail: "hello@agritrackture.com",
    supportPhone: "+63 917 555 0100",
    allowRegistration: true,
    guidePriceNote:
      "Guide prices are weekly market averages uploaded by AgriTrackture. Farmers must set listing prices within each product’s min–max range so buyers see a fair comparison.",
    noPaymentNote:
      "AgriTrackture does not process payments. Buyers contact the farmer using the listed phone and location to arrange pickup or delivery.",
    orderFlow: ["queued", "confirmed", "preparing", "ready", "completed"],
    citiesServed: ["Nueva Ecija", "Benguet", "Davao del Sur", "Bukidnon", "Metro Manila", "Cebu"],
  };

  return {
    users,
    products,
    guidePrices,
    orders,
    conversations,
    messages,
    notifications,
    settings,
    sessions: {},
    nextId: 2000,
  };
}
